comment proxy chains logic and force compile failure

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -29,20 +29,32 @@ BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
 BUILDPACK_DIR="$(dirname "$(dirname "$0")")"
-log_buildpack_progress "CACHE_DIR: $CACHE_DIR"
+
 TAILSCALE_VERSION=${TAILSCALE_VERSION:-$(latest_tailscale_version)}
 TAILSCALE_BUILD_ARCH=amd64
 TAILSCALE_SOURCE_URL="https://pkgs.tailscale.com/stable/tailscale_${TAILSCALE_VERSION}_${TAILSCALE_BUILD_ARCH}.tgz"
 TAILSCALE_INSTALL_DIR="$BUILD_DIR/vendor/tailscale"
 
-# TODO: consider using the latest version of ProxyChains-ng
-PROXYCHAINS_VERSION=${PROXYCHAINS_VERSION:-4.17}
-PROXYCHAINS_SOURCE_URL="https://github.com/rofl0r/proxychains-ng/archive/refs/tags/v$PROXYCHAINS_VERSION.tar.gz"
-PROXYCHAINS_INSTALL_DIR="$BUILD_DIR/vendor/proxychains-ng"
-
-# TODO: a new version of Tailscale is available check.
+## TODO: consider using the latest version of ProxyChains-ng
+#PROXYCHAINS_VERSION=${PROXYCHAINS_VERSION:-4.17}
+#PROXYCHAINS_SOURCE_URL="https://github.com/rofl0r/proxychains-ng/archive/refs/tags/v$PROXYCHAINS_VERSION.tar.gz"
+#PROXYCHAINS_INSTALL_DIR="$BUILD_DIR/vendor/proxychains-ng"
 
 log_buildpack_step "Installing Tailscale $TAILSCALE_VERSION"
+# TODO: a new version of Tailscale is available check.
+#remote: ###### WARNING:
+#remote:
+#remote:        There is a more recent Ruby version available for you to use:
+#remote:
+#remote:        3.2.9
+#remote:
+#remote:        The latest version will include security and bug fixes. We always recommend
+#remote:        running the latest version of your minor release.
+#remote:
+#remote:        Please upgrade your Ruby version.
+#remote:
+#remote:        For all available Ruby versions see:
+#remote:          https://devcenter.heroku.com/articles/ruby-support#supported-runtimes
 mkdir -p $TAILSCALE_INSTALL_DIR
 mkdir -p "$TAILSCALE_INSTALL_DIR/bin/buildpack_helpers"
 
@@ -60,29 +72,34 @@ chmod +x "$TAILSCALE_INSTALL_DIR/heroku-tailscale-test.sh"
 mkdir -p $BUILD_DIR/.profile.d
 echo 'export PATH="/app/vendor/tailscale:$PATH"' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh
 
-log_buildpack_progress "Installing ProxyChains-ng $PROXYCHAINS_VERSION"
-PROXYCHAINS_BUILD_DIR="$CACHE_DIR/proxychains-ng-$PROXYCHAINS_VERSION"
-if [ ! -f "$PROXYCHAINS_BUILD_DIR/proxychains4" ]; then
-  rm -rf $PROXYCHAINS_BUILD_DIR
-  wget $PROXYCHAINS_SOURCE_URL -O $CACHE_DIR/proxychains.tar.gz
-  cd $CACHE_DIR
-  tar -zxvf $CACHE_DIR/proxychains.tar.gz
-  cd $PROXYCHAINS_BUILD_DIR
-  make clean
-  ./configure --libdir=/app/vendor/proxychains-ng
-  make
-fi
-mkdir $PROXYCHAINS_INSTALL_DIR
-cp $PROXYCHAINS_BUILD_DIR/libproxychains4.so $PROXYCHAINS_BUILD_DIR/proxychains4 $BUILDPACK_DIR/conf/proxychains.conf $PROXYCHAINS_INSTALL_DIR
-echo 'export PATH="/app/vendor/proxychains-ng:$PATH"' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh
+#log_buildpack_progress "Installing ProxyChains-ng $PROXYCHAINS_VERSION"
+#PROXYCHAINS_BUILD_DIR="$CACHE_DIR/proxychains-ng-$PROXYCHAINS_VERSION"
+#if [ ! -f "$PROXYCHAINS_BUILD_DIR/proxychains4" ]; then
+#  rm -rf $PROXYCHAINS_BUILD_DIR
+#  wget $PROXYCHAINS_SOURCE_URL -O $CACHE_DIR/proxychains.tar.gz
+#  cd $CACHE_DIR
+#  tar -zxvf $CACHE_DIR/proxychains.tar.gz
+#  cd $PROXYCHAINS_BUILD_DIR
+#  make clean
+#  ./configure --libdir=/app/vendor/proxychains-ng
+#  make
+#fi
+#mkdir $PROXYCHAINS_INSTALL_DIR
+#cp $PROXYCHAINS_BUILD_DIR/libproxychains4.so $PROXYCHAINS_BUILD_DIR/proxychains4 $BUILDPACK_DIR/conf/proxychains.conf $PROXYCHAINS_INSTALL_DIR
+#echo 'export PATH="/app/vendor/proxychains-ng:$PATH"' >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh
 
 log_buildpack_progress "Configuring Tailscale to start when booting"
 # Add the line to start tailscale to the end of the file
 echo "/app/vendor/tailscale/heroku-tailscale-start.sh" >> $BUILD_DIR/.profile.d/heroku-tailscale-buildpack.sh
 
-log_buildpack_progress "Moving the tailscale_proxy into app/bin"
-mkdir -p $BUILD_DIR/bin
-cp "$BUILDPACK_DIR/bin/tailscale_proxy" $BUILD_DIR/bin/
-chmod +x $BUILD_DIR/bin/tailscale_proxy
+#log_buildpack_progress "Moving the tailscale_proxy into app/bin"
+#mkdir -p $BUILD_DIR/bin
+#cp "$BUILDPACK_DIR/bin/tailscale_proxy" $BUILD_DIR/bin/
+#chmod +x $BUILD_DIR/bin/tailscale_proxy
 
-log_buildpack_step "Build succeeded!"
+#if $?; then
+#  log_buildpack_step "Tailscale $TAILSCALE_VERSION installed successfully!"
+#else
+  log_buildpack_step "Failed to install Tailscale $TAILSCALE_VERSION"
+  exit 1
+#fi
